import 'package:flutter/material.dart';

class AppI18n {
  static const supported = <Locale>[
    Locale('fa'), Locale('en'), Locale('da'), Locale('de'), Locale('de', 'CH'),
    Locale('ar'), Locale('hi'), Locale('he'), Locale('es'), Locale('it'),
    Locale('sv'), Locale('fi'), Locale('no'), Locale('is'), Locale('el'), Locale('tr'),
  ];

  static const names = <String, String>{
    'fa':'فارسی','en':'English','da':'Dansk','de':'Deutsch','de-CH':'Schweizerdeutsch',
    'ar':'العربية','hi':'हिन्दी','he':'עברית','es':'Español','it':'Italiano',
    'sv':'Svenska','fi':'Suomi','no':'Norsk','is':'Íslenska','el':'Ελληνικά','tr':'Türkçe',
  };

  static const data = <String, Map<String, String>>{
    'en': {'home':'Home','recent':'Recent','cloud':'Cloud','favorites':'Favorites','settings':'Settings','open':'Open file','new':'New document','pdf':'PDF','word':'Word','powerpoint':'PowerPoint','excel':'Excel','quick':'Quick actions','templates':'Templates','scan':'Scan document','search':'Search','appearance':'Appearance','language':'Language','themes':'Themes','general':'General','editor':'Editor','security':'Privacy & security','performance':'Performance','accessibility':'Accessibility','light':'Light','dark':'Dark','amoled':'AMOLED','system':'System','save':'Save','export':'Export','comments':'Comments','insert':'Insert','review':'Review','view':'View'},
    'fa': {'home':'خانه','recent':'اخیر','cloud':'ابری','favorites':'موردعلاقه‌ها','settings':'تنظیمات','open':'باز کردن فایل','new':'سند جدید','pdf':'PDF','word':'Word','powerpoint':'PowerPoint','excel':'Excel','quick':'عملیات سریع','templates':'قالب‌ها','scan':'اسکن سند','search':'جست‌وجو','appearance':'ظاهر','language':'زبان','themes':'تم‌ها','general':'عمومی','editor':'ویرایشگر','security':'حریم خصوصی و امنیت','performance':'کارایی','accessibility':'دسترسی‌پذیری','light':'روشن','dark':'تاریک','amoled':'AMOLED','system':'سیستم','save':'ذخیره','export':'خروجی','comments':'نظرات','insert':'درج','review':'بازبینی','view':'نمایش'},
    'da': {'home':'Hjem','recent':'Seneste','cloud':'Sky','favorites':'Favoritter','settings':'Indstillinger','open':'Åbn fil','new':'Nyt dokument','pdf':'PDF','word':'Word','powerpoint':'PowerPoint','excel':'Excel','quick':'Hurtige handlinger','templates':'Skabeloner','scan':'Scan dokument','search':'Søg','appearance':'Udseende','language':'Sprog','themes':'Temaer','general':'Generelt','editor':'Editor','security':'Privatliv og sikkerhed','performance':'Ydeevne','accessibility':'Tilgængelighed','light':'Lys','dark':'Mørk','amoled':'AMOLED','system':'System','save':'Gem','export':'Eksportér','comments':'Kommentarer','insert':'Indsæt','review':'Gennemse','view':'Vis'},
    'de': {'home':'Start','recent':'Zuletzt','cloud':'Cloud','favorites':'Favoriten','settings':'Einstellungen','open':'Datei öffnen','new':'Neues Dokument','pdf':'PDF','word':'Word','powerpoint':'PowerPoint','excel':'Excel','quick':'Schnellaktionen','templates':'Vorlagen','scan':'Dokument scannen','search':'Suchen','appearance':'Darstellung','language':'Sprache','themes':'Themes','general':'Allgemein','editor':'Editor','security':'Datenschutz & Sicherheit','performance':'Leistung','accessibility':'Barrierefreiheit','light':'Hell','dark':'Dunkel','amoled':'AMOLED','system':'System','save':'Speichern','export':'Exportieren','comments':'Kommentare','insert':'Einfügen','review':'Überprüfen','view':'Ansicht'},
    'ar': {'home':'الرئيسية','recent':'الأخيرة','cloud':'السحابة','favorites':'المفضلة','settings':'الإعدادات','open':'فتح ملف','new':'مستند جديد','pdf':'PDF','word':'Word','powerpoint':'PowerPoint','excel':'Excel','quick':'إجراءات سريعة','templates':'قوالب','scan':'مسح المستند','search':'بحث','appearance':'المظهر','language':'اللغة','themes':'السمات','general':'عام','editor':'المحرر','security':'الخصوصية والأمان','performance':'الأداء','accessibility':'إمكانية الوصول','light':'فاتح','dark':'داكن','amoled':'AMOLED','system':'النظام','save':'حفظ','export':'تصدير','comments':'التعليقات','insert':'إدراج','review':'مراجعة','view':'عرض'},
    'es': {'home':'Inicio','recent':'Recientes','cloud':'Nube','favorites':'Favoritos','settings':'Ajustes','open':'Abrir archivo','new':'Nuevo documento','pdf':'PDF','word':'Word','powerpoint':'PowerPoint','excel':'Excel','quick':'Acciones rápidas','templates':'Plantillas','scan':'Escanear documento','search':'Buscar','appearance':'Apariencia','language':'Idioma','themes':'Temas','general':'General','editor':'Editor','security':'Privacidad y seguridad','performance':'Rendimiento','accessibility':'Accesibilidad','light':'Claro','dark':'Oscuro','amoled':'AMOLED','system':'Sistema','save':'Guardar','export':'Exportar','comments':'Comentarios','insert':'Insertar','review':'Revisar','view':'Vista'},
    'it': {'home':'Home','recent':'Recenti','cloud':'Cloud','favorites':'Preferiti','settings':'Impostazioni','open':'Apri file','new':'Nuovo documento','pdf':'PDF','word':'Word','powerpoint':'PowerPoint','excel':'Excel','quick':'Azioni rapide','templates':'Modelli','scan':'Scansiona documento','search':'Cerca','appearance':'Aspetto','language':'Lingua','themes':'Temi','general':'Generale','editor':'Editor','security':'Privacy e sicurezza','performance':'Prestazioni','accessibility':'Accessibilità','light':'Chiaro','dark':'Scuro','amoled':'AMOLED','system':'Sistema','save':'Salva','export':'Esporta','comments':'Commenti','insert':'Inserisci','review':'Revisione','view':'Visualizza'},
    'tr': {'home':'Ana Sayfa','recent':'Son Kullanılanlar','cloud':'Bulut','favorites':'Favoriler','settings':'Ayarlar','open':'Dosya aç','new':'Yeni belge','pdf':'PDF','word':'Word','powerpoint':'PowerPoint','excel':'Excel','quick':'Hızlı işlemler','templates':'Şablonlar','scan':'Belge tara','search':'Ara','appearance':'Görünüm','language':'Dil','themes':'Temalar','general':'Genel','editor':'Düzenleyici','security':'Gizlilik ve güvenlik','performance':'Performans','accessibility':'Erişilebilirlik','light':'Açık','dark':'Koyu','amoled':'AMOLED','system':'Sistem','save':'Kaydet','export':'Dışa aktar','comments':'Yorumlar','insert':'Ekle','review':'Gözden geçir','view':'Görünüm'},
  };

  static String t(Locale locale, String key) =>
      data[locale.toLanguageTag()]?[key] ?? data[locale.languageCode]?[key] ?? data['en']![key] ?? key;

  static bool isRtl(Locale locale) => {'fa','ar','he'}.contains(locale.languageCode);
}
